# Streamlit secrets file https://docs.streamlit.io/deploy/streamlit-community-cloud/deploy-your-app/secrets-management

AT_API_KEY = ""     # africastalking API Key https://developers.africastalking.com/
AT_USERNAME = ""    # africastalking Username
OPENAI_API_KEY = "" # OpenAI API Key, for GPT-4
LIQUID_API_KEY = "" # Liquid API Key, for VES demo
